maven_layout()

jar_library(name='util-core',
  dependencies=[
    pants('util/util-core/src/main/scala'),
    pants('util/util-core/src/main/java')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('util/util-core/src/test/java'),
    pants('util/util-core/src/test/scala')
  ]
)
