junit_tests(
    sources = ["*.scala"],
    compiler_option_sets = {"fatal_warnings"},
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/scalatest",
        "util/util-core/src/main/scala/com/twitter/io",
        "util/util-core/src/main/scala/com/twitter/util",
        "util/util-security/src/main/scala/com/twitter/util/security",
        "util/util-security/src/test/resources",
    ],
)
