maven_layout()

jar_library(name='util-zk-common',
  dependencies=[
    'util/util-zk-common/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'util/util-zk-common/src/test/scala'
  ]
)
