junit_tests(
    sources = ["*.scala"],
    compiler_option_sets = ["fatal_warnings"],
    strict_deps = True,
    dependencies = [
        "3rdparty/jvm/org/scalatest",
        "util/util-core/src/main/scala/com/twitter/util",
        "util/util-intellij/src/main/resources",
    ],
)
