junit_tests(
    sources = ["*.scala"],
    compiler_option_sets = ["fatal_warnings"],
    strict_deps = True,
    tags = ["non-exclusive"],
    dependencies = [
        "3rdparty/jvm/org/scala-lang/modules:scala-xml",
        "3rdparty/jvm/org/scalatest",
        "3rdparty/jvm/org/scalatestplus:junit",
        "util/util-core:util-core-util",
        "util/util-intellij/src/main/resources",
    ],
)
