target(
    dependencies = [
        "util/util-cache/src/main/scala",
    ],
)

test_suite(
    name = "tests",
    dependencies = [
        "util/util-cache/src/test/java",
        "util/util-cache/src/test/scala",
    ],
)
