target(
    tags = ["bazel-compatible"],
    dependencies = [
        "util/util-cache/src/main/scala",
    ],
)

test_suite(
    name = "tests",
    tags = ["bazel-compatible"],
    dependencies = [
        "util/util-cache/src/test/java",
        "util/util-cache/src/test/scala",
    ],
)
