target(name='util-cache',
  dependencies=[
    'util/util-cache/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'util/util-cache/src/test/java',
    'util/util-cache/src/test/scala'
  ]
)
