maven_layout()

jar_library(name='util-thrift',
  dependencies=[
    pants('util/util-thrift/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('util/util-thrift/src/test/scala')
  ]
)
