junit_tests(
    sources = ["*.java"],
    compiler_option_sets = ["fatal_warnings"],
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/scala-lang:scala-library",
        "util/util-app/src/main/java/com/twitter/app",
        "util/util-app/src/main/scala",
        "util/util-core/src/main/scala/com/twitter/util",
        "util/util-function/src/main/java/com/twitter/function",
    ],
)
