junit_tests(
    sources = rglobs("*.scala", "*.java"),
    fatal_warnings = True,
    dependencies = [
        "3rdparty/jvm/org/mockito:mockito-all",
        "3rdparty/jvm/org/scalatest",
        "3rdparty/jvm/org/slf4j:slf4j-api",
        "3rdparty/jvm/org/slf4j:slf4j-simple",
        "util/util-core/src/main/scala",
        "util/util-slf4j-api/src/main/scala",
        "util/util-slf4j-api/src/test/resources",
    ],
)
