junit_tests(
  dependencies=[
    '3rdparty/jvm/org/mockito:mockito-all',
    '3rdparty/jvm/org/scalatest',
    '3rdparty/jvm/org/slf4j:slf4j-api',
    '3rdparty/jvm/org/slf4j:slf4j-simple',
    'util/util-core/src/main/scala:scala',
    'util/util-slf4j-api/src/main/scala:scala',
  ],
  resources=[
    'util/util-slf4j-api/src/test/resources',
  ],
  fatal_warnings=True,
  sources=rglobs('*.scala', '*.java'),
)
