junit_tests(
    sources = rglobs("*.java"),
    fatal_warnings = True,
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/scala-lang:scala-library",
        "util/util-registry/src/main/scala",
    ],
)
