junit_tests(
    sources = ["*.java"],
    compiler_option_sets = {"fatal_warnings"},
    dependencies = [
        "3rdparty/jvm/junit",
        "util/util-core/src/main/scala/com/twitter/util",
        "util/util-security/src/main/scala/com/twitter/util/security",
    ],
)
