test_suite(
    dependencies = [
        "util/util-core/src/test/scala/com/twitter/concurrent",
        "util/util-core/src/test/scala/com/twitter/conversions",
        "util/util-core/src/test/scala/com/twitter/io",
        "util/util-core/src/test/scala/com/twitter/util",
    ],
)
