java_library(
    sources = [
        "*.java",
        "constraints/*.java",
    ],
    compiler_option_sets = ["fatal_warnings"],
    strict_deps = True,
    dependencies = [
        "3rdparty/jvm/jakarta/validation:jakarta.validation-api",
    ],
    exports = [
        "3rdparty/jvm/jakarta/validation:jakarta.validation-api",
    ],
)
