test_suite(
    tags = ["bazel-compatible"],
    dependencies = [
        "util/util-cache/src/test/scala/com/twitter/cache",
        "util/util-cache/src/test/scala/com/twitter/cache/caffeine",
    ],
)
