maven_layout()

jar_library(name='util-events',
  dependencies=[
    'util/util-events/src/main/scala',
    'util/util-events/src/main/java'
  ]
)

jar_library(name='tests',
  dependencies=[
    'util/util-events/src/test/scala',
    'util/util-events/src/test/java'
  ]
)
