maven_layout()

jar_library(name='util-hashing',
  dependencies=[
    'util/util-hashing/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'util/util-hashing/src/test/scala'
  ]
)
