target(name='util-stats',
  dependencies=[
    'util/util-stats/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'util/util-stats/src/test/scala',
    'util/util-stats/src/test/java'
  ]
)
