junit_tests(
    sources = globs("*.java"),
    compiler_option_sets = {"fatal_warnings"},
    dependencies = [
        "3rdparty/jvm/junit",
        "util/util-jvm/src/main/scala/com/twitter/jvm",
    ],
)
