junit_tests(
    sources = ["**/*.java"],
    compiler_option_sets = ["fatal_warnings"],
    dependencies = [
        "3rdparty/jvm/junit",
        "util/util-core:util-core-util",
        "util/util-stats/src/main/scala/com/twitter/finagle/stats",
    ],
)
