target(
  dependencies=[
    'util/util-app/src/main/scala',
    'util/util-app/src/main/java'
  ]
)

target(name='tests',
  dependencies=[
    'util/util-app/src/test/scala',
    'util/util-app/src/test/java',
  ]
)
