maven_layout()

jar_library(name='util-app',
  dependencies=[
    pants('util/util-app/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('util/util-app/src/test/scala')
  ]
)
