junit_tests(
    sources = rglobs("*.java"),
    compiler_option_sets = {"fatal_warnings"},
    dependencies = [
        "3rdparty/jvm/junit",
        "util/util-core/src/main/scala",
        "util/util-security/src/main/scala",
    ],
)
