junit_tests(
    sources = rglobs("*.java"),
    fatal_warnings = True,
    dependencies = [
        "3rdparty/jvm/junit",
        "util/util-core/src/main/scala",
        "util/util-security/src/main/scala",
    ],
)
