junit_tests(
    sources = rglobs("*.java"),
    fatal_warnings = True,
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/scala-lang:scala-library",
        "util/util-app/src/main/java",
        "util/util-app/src/main/scala",
        "util/util-core/src/main/scala",
        "util/util-function/src/main/java",
    ],
)
