maven_layout()

jar_library(name='util-jvm',
  dependencies=[
    pants('util/util-jvm/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('util/util-jvm/src/test/scala')
  ]
)
