target(
    dependencies = [
        "util/util-jvm/src/main/scala",
    ],
)

target(
    name = "tests",
    dependencies = [
        "util/util-jvm/src/test/java",
        "util/util-jvm/src/test/scala",
    ],
)
