scala_library(
    compiler_option_sets = ["fatal_warnings"],
    provides = scala_artifact(
        org = "com.twitter",
        name = "util-security",
        repo = artifactory,
    ),
    dependencies = [
        "util/util-core:util-core-util",
        "util/util-logging/src/main/scala/com/twitter/logging",
    ],
)
