scala_library(name='scala',
  provides = scala_artifact(
    org = 'com.twitter',
    name = 'util-core',
    repo = artifactory,
  ),
  dependencies=[
    'util/util-function/src/main/java',
  ],
  sources=rglobs('*.scala')
)
