java_library(
    sources = ["*.java"],
    compiler_option_sets = ["fatal_warnings"],
    strict_deps = "True",
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/jakarta/validation:jakarta.validation-api",
    ],
)
