java_library(
    compiler_option_sets = ["fatal_warnings"],
    provides = artifact(
        org = "com.twitter",
        name = "util-function-java",
        repo = artifactory,
    ),
    strict_deps = True,
    tags = ["bazel-compatible"],
)
