junit_tests(
    sources = ["**/*.scala"],
    compiler_option_sets = ["fatal_warnings"],
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/mockito:mockito-all",
        "3rdparty/jvm/org/scalatest",
        "util/util-app/src/main/scala",
        "util/util-app/src/test/resources",
        "util/util-core:util-core-util",
        "util/util-registry/src/main/scala/com/twitter/util/registry",
    ],
)
