maven_layout()

jar_library(name='util-codec',
  dependencies=[
    pants('util/util-codec/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('util/util-codec/src/test/scala')
  ]
)
