test_suite(
    dependencies = [
        "util/util-core/src/test/java/com/twitter/concurrent",
        "util/util-core/src/test/java/com/twitter/io",
        "util/util-core/src/test/java/com/twitter/service",
        "util/util-core/src/test/java/com/twitter/util",
        "util/util-core/src/test/java/com/twitter/util/javainterop",
    ],
)
