junit_tests(
    sources = rglobs("*.java"),
    compiler_option_sets = {"fatal_warnings"},
    dependencies = [
        "3rdparty/jvm/com/github/ben-manes/caffeine",
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/mockito:mockito-all",
        "3rdparty/jvm/org/scala-lang:scala-library",
        "3rdparty/jvm/org/scalacheck",
        "util/util-core/src/main/java",
        "util/util-core/src/main/scala",
        "util/util-function/src/main/java",
    ],
)
