junit_tests(
  dependencies=[
    '3rdparty/jvm/com/google/guava',
    '3rdparty/jvm/junit:junit',
    '3rdparty/jvm/org/mockito:mockito-all',
    '3rdparty/jvm/org/scala-lang:scala-library',
    '3rdparty/jvm/org/scalacheck:scalacheck',
    'util/util-core/src/main/java',
    'util/util-core/src/main/scala',
    'util/util-function/src/main/java:java',
  ],
  fatal_warnings=True,
  sources=rglobs('*.java'),
  strict_deps=True,

)
