junit_tests(
    sources = ["*.scala"],
    compiler_option_sets = {"fatal_warnings"},
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/scalacheck",
        "3rdparty/jvm/org/scalatest",
        "util/util-core/src/main/scala/com/twitter/io",
        "util/util-hashing/src/main/scala/com/twitter/hashing",
        "util/util-hashing/src/test/resources",
    ],
)
