junit_tests(
    sources = ["*.scala"],
    compiler_option_sets = ["fatal_warnings"],
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/scalatest",
        "util/util-app-lifecycle/src/main/scala/com/twitter/app/lifecycle",
        "util/util-core:util-core-util",
    ],
)
