scala_library(
    compiler_option_sets = ["fatal_warnings"],
    provides = scala_artifact(
        org = "com.twitter",
        name = "util-hashing",
        repo = artifactory,
    ),
    tags = ["bazel-compatible"],
)
