junit_tests(
    sources = rglobs("*.scala"),
    fatal_warnings = True,
    dependencies = [
        "3rdparty/jvm/com/google/code/findbugs:jsr305",
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/mockito:mockito-all",
        "3rdparty/jvm/org/scalatest",
        "util/util-cache-guava/src/main/scala",
        "util/util-cache/src/main/scala",
        "util/util-cache/src/test/scala:abstract_tests",
        "util/util-core/src/main/scala",
    ],
)
