maven_layout()

jar_library(name='util-collection',
  dependencies=[
    'util/util-collection/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'util/util-collection/src/test/scala'
  ]
)
