maven_layout()

jar_library(name='util-collection',
  dependencies=[
    pants('util/util-collection/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('util/util-collection/src/test/scala')
  ]
)
