junit_tests(
    sources = ["*.scala"],
    compiler_option_sets = {"fatal_warnings"},
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/scalatest",
        "util/util-thrift/src/main/scala/com/twitter/util",
        "util/util-thrift/src/test/java/com/twitter/util",
    ],
)
