maven_layout()

jar_library(name='util-logging',
  dependencies=[
    'util/util-logging/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'util/util-logging/src/test/scala',
    'util/util-logging/src/test/java'
  ]
)
