scala_library(name='scala',
  provides = scala_artifact(
    org = 'com.twitter',
    name = 'twitter-server',
    repo = artifactory,
  ),
  dependencies=[
    'util/util-app/src/main/scala',
  ],
  sources=rglobs('*.scala'),
)
