scala_library(
    sources = ["*.scala"],
    compiler_option_sets = ["fatal_warnings"],
    dependencies = [
        "util/util-core:util-core-util",
        "util/util-routing/src/main/scala/com/twitter/util/routing",
    ],
)
