java_library(
    sources = ["*.java"],
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    provides = artifact(
        org = "com.twitter",
        name = "util-core-java-service",
        repo = artifactory,
    ),
    strict_deps = True,
    tags = ["bazel-compatible"],
)
