java_library(
    sources = globs("*.java"),
    compiler_option_sets = {"fatal_warnings"},
    provides = artifact(
        org = "com.twitter",
        name = "util-core-java-service",
        repo = artifactory,
    ),
)
