maven_layout()

jar_library(name='util-zk-test',
  dependencies=[
    'util/util-zk-test/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'util/util-zk-test/src/test/java',
    'util/util-zk-test/src/test/scala'
  ]
)
