junit_tests(
    sources = rglobs("*.scala"),
    fatal_warnings = True,
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/mockito:mockito-all",
        "3rdparty/jvm/org/scalacheck",
        "3rdparty/jvm/org/scalatest",
        "util/util-core/src/main/scala",
        "util/util-hashing/src/main/scala",
        "util/util-hashing/src/test/resources",
    ],
)
