junit_tests(
  fatal_warnings = True,
  strict_deps = True,
  dependencies = [
    '3rdparty/jvm/junit',
    '3rdparty/jvm/org/scalatest',
    'util/util-logging',
    'util/util-security/src/main/scala',
    'util/util-security/src/test/resources',
    'util/util-core/src/main/scala:scala',
  ],
  sources = rglobs('*.scala'),
)
