junit_tests(
    sources = globs("*.scala"),
    compiler_option_sets = {"fatal_warnings"},
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/scalatest",
        "util/util-core/src/main/scala/com/twitter/util",
        "util/util-reflect/src/main/scala/com/twitter/util/reflect",
    ],
)
