target(
    tags = [
        # Legacy code that shouldn't be used for new services.
        "deprecated",
    ],
    dependencies = [
        "util/util-reflect/src/main/scala",
    ],
)

test_suite(
    name = "tests",
    dependencies = [
        "util/util-reflect/src/test/scala",
    ],
)
