maven_layout()

jar_library(name='util-reflect',
  dependencies=[
    pants('util/util-reflect/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('util/util-reflect/src/test/scala')
  ]
)
