target(
    tags = ["bazel-compatible"],
    dependencies = [
        "util/util-reflect/src/main/scala",
    ],
)

test_suite(
    name = "tests",
    tags = ["bazel-compatible"],
    dependencies = [
    ],
)
