junit_tests(
    sources = ["*.java"],
    compiler_option_sets = ["fatal_warnings"],
    dependencies = [
        "3rdparty/jvm/junit",
        "util/util-logging/src/main/scala/com/twitter/logging",
    ],
)
