junit_tests(
    sources = rglobs("*.java"),
    fatal_warnings = True,
    dependencies = [
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/mockito:mockito-all",
        "3rdparty/jvm/org/scala-lang:scala-library",
        "util/util-cache",
        "util/util-cache-guava/src/main/scala",
        "util/util-core/src/main/scala",
    ],
)
