junit_tests(
    sources = ["*.java"],
    compiler_option_sets = {"fatal_warnings"},
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/scala-lang:scala-library",
        "util/util-tunable/src/main/scala/com/twitter/util/tunable",
    ],
)
