maven_layout()

jar_library(name='util-registry',
  dependencies=[
    'util/util-registry/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'util/util-registry/src/test/scala'
  ]
)
