target(name='util-registry',
  dependencies=[
    'util/util-registry/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'util/util-registry/src/test/scala',
    'util/util-registry/src/test/java'
  ]
)
