junit_tests(
    sources = globs("*.java"),
    compiler_option_sets = {"fatal_warnings"},
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/scala-lang:scala-library",
        "util/util-core/src/main/java/com/twitter/io",
        "util/util-core/src/main/scala",
    ],
)
