junit_tests(
    sources = ["**/*.scala"],
    compiler_option_sets = ["fatal_warnings"],
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/apache/zookeeper:zookeeper-server",
        "3rdparty/jvm/org/scalatest",
        "util/util-core/src/main/scala/com/twitter/io",
        "util/util-zk-test/src/main/scala/com/twitter/zk",
    ],
)
