name: continuous integration

env:
  JAVA_OPTS: "-Dsbt.log.noformat=true"
  TRAVIS: "true" # pretend we're TravisCI
  UPLOAD_COVERAGE: false

defaults:
  run:
    shell: bash
on:
  push:
    branches:
      - develop
      - release
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        scala: [2.11.12, 2.12.8, 2.13.1]
        java: ['1.8', '1.11']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: echo java version
        run: java -Xmx32m -version
      - name: echo javac version
        run: javac -J-Xmx32m -version
      - name: cache build dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-build-deps
        with:
          path: |
            ~/.ivy2/cache
            ~/.ivy2/local/com.twitter
            ~/.sbt
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.scala }}-${{ matrix.java }}
      - name: update cache
        run: |
          if [ -f ~/.ivy2/cache ]; then
            find ~/.ivy2/cache  -name "ivydata-*.properties" -delete
          fi 
          if [ -f ~/.sbt ]; then
            find ~/.sbt         -name "*.lock"               -delete
          fi
      - name: test
        run: ${{ format('./sbt ++{0} clean coverage test coverageReport', matrix.scala) }}
      - name: test util-intellij with scala 2.11
        if: ${{ startsWith(matrix.scala, '2.11') }}
        run: ${{ format('./sbt ++{0} "project util-intellij" coverage test coverageReport', matrix.scala) }}
      - name: coverage
        if: ${{ success() }}
        run: ${{format('./sbt ++{0} coverageAggregate', matrix.scala) }}
      - name: upload coverage
        if: ${{ env.UPLOAD_COVERAGE == true }}  
        run: bash <(curl -s https://codecov.io/bash)
