# note that this will not compile on its own, it's just here 
# for the scala library to pull in
java_library(name='java',
  sources=rglobs('*.java'),
  dependencies=[
    'util/util-core/src/main/scala'
  ]
)
